name: Notify Discord on Push

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          MESSAGE="🚀 New update on https://tauriachievements.github.io/**

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n --arg content "$MESSAGE" '{content: $content}')" \
               "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}