name: Notify Discord on Push

on:
  push:

jobs:
  notify:
    if: github.event.head_commit.message == 'sync data'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for site deployment
        run: sleep 120

      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "🚀 New update is available on Tauri Achievements"}' \
               "$DISCORD_WEBHOOK_URL"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
